name: Build RP2040 UF2

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Pico SDK
      - name: Clone pico-sdk
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init

      - name: Set PICO_SDK_PATH
        run: echo "PICO_SDK_PATH=${{ github.workspace }}/pico-sdk" >> $GITHUB_ENV

      # Toolchain
      - name: Install ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      # Build
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Compile
        run: |
          cd build
          make -j4

      # Artifact
      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: firmware-uf2
          path: build/*.uf2
